### ISSUE TITLE
ResponseReasoningSummaryDoneEvent missing from openai.types.responses in v1.99.0

### ISSUE THREAD

**Issue by yrobel-lima** [openai/openai-python#2511]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [x] This is an issue with the Python library

### Describe the bug

ResponseReasoningSummaryDoneEvent cannot be imported from openai.types.responses in openai==1.99.0, though it works in 1.97.1

Error: cannot import name 'ResponseReasoningSummaryDoneEvent' from 'openai.types.responses' (.venv\Lib\site-packages\openai\types\responses\__init__.py)

### To Reproduce

from openai.types.responses import ResponseReasoningSummaryDoneEvent

### Code snippets

```Python

```

### OS

Windows

### Python version

Python 3.11.11

### Library version

opeanai 1.99.0

**Comment by jezell** [comment]
Looks like missing export of ResponseReasoningSummaryDoneEvent here?

https://github.com/openai/openai-python/blob/b0ad27a67681f1b6fb473cc75c642efa1f4941d5/src/openai/types/responses/__init__.py

**Comment by jezell** [comment]
duplicate here https://github.com/openai/openai-python/issues/2510

**Comment by jezell** [comment]
https://github.com/openai/openai-python/commit/2a6d1436288a07f67f6afefe5c0b5d6ae32d7e70

Looks fixed in 1.99.1

**Comment by RobertCraigie** [comment]
Sorry for the regression here, this has been fixed.
