### ISSUE TITLE
Regression: response.output_text is broken since 1.99.2

### ISSUE THREAD

**Issue by hheimbuerger** [openai/openai-python#2523]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [x] This is an issue with the Python library

### Describe the bug

In 1.99.2, Response objects are missing the `output_text` attribute. Test case is the [very first example from the README](https://github.com/openai/openai-python?tab=readme-ov-file#usage). But here's an even simpler way to reproduce:

It worked in 1.99.1:

```
> uv run --with="openai==1.99.1" python -c "from openai import OpenAI; print(OpenAI().responses.create(model='gpt-4o', input='sup?').output_text)"
Hey! Not much, just here to help. What's up with you?
```

The same code is broken in 1.99.2:

```
> uv run --with="openai==1.99.2" python -c "from openai import OpenAI; OpenAI().responses.create(model='gpt-4o', input='sup?').output_text"
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\uv\cache\archive-v0\IzxeX74ZmC-P7DA6mL-0x\Lib\site-packages\pydantic\main.py", line 983, in __getattr__
    return pydantic_extra[item]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'output_text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\me\AppData\Local\uv\cache\archive-v0\IzxeX74ZmC-P7DA6mL-0x\Lib\site-packages\pydantic\main.py", line 985, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'Response' object has no attribute 'output_text'
```

### To Reproduce

1. Run `uv run --with="openai==1.99.2" python -c "from openai import OpenAI; OpenAI().responses.create(model='gpt-4o', input='sup?').output_text"`

Expected: any GPT response
Actual: `AttributeError`

### Code snippets

```bash
uv run --with="openai==1.99.2" python -c "from openai import OpenAI; OpenAI().responses.create(model='gpt-4o', input='sup?').output_text"
```

### OS

Windows 11

### Python version

Python v3.11.1

### Library version

openai v1.99.2

**Comment by mdrxy** [comment]
#2521

**Comment by RobertCraigie** [comment]
Thanks for the report and sorry for the regression, this has been fixed.
