### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'Embedding'

### ISSUE THREAD

**Issue by Travis-Barton** [openai/openai-python#78]
I've installed openai via: 

`pip install openai`
`pip install --upgrade openai` 

and yet when I try to run an example like:

```
import openai
print(openai.Embedding)
```

 I get the error 

```
Traceback (most recent call last):
  File "/Users/travisbarton/.conda/envs/work3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-c5f5985add60>", line 1, in <module>
    openai.Embedding
AttributeError: module 'openai' has no attribute 'Embedding'
```

the version I have is `0.8.0`

this happens for full examples, but this is just the most simple case.
any idea why?

**Comment by hallacy** [comment]
Hey @Travis-Barton, thanks for the issue! 

This repo is currently on version 0.15.0 which makes me think something is up with that upgrade command.  Does `pip show openai` show an up to date version?

**Comment by Travis-Barton** [comment]
@hallacy  It shows:
```
Name: openai
Version: 0.8.0
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com
License: UNKNOWN
Location: /Users/travisbarton/.conda/envs/work3.6/lib/python3.6/site-packages
Requires: requests, tqdm
Required-by: open-humans

```

**Comment by hallacy** [comment]
Ah, python 3.6 would do it.

We stopped supporting python 3.6 so that we could support pandas 1.2 which requires python 3.7+.  That wasn't actually updated until 0.10.5 so the last version that works with 3.6 is 0.8.0.

**Comment by Travis-Barton** [comment]
That makes sense, thanks!

**Comment by codemaker2015** [comment]
Try to use openai version 0.28.1

`pip install openai==0.28.1`
